### ISSUE TITLE
0.2.1/dev/search : docker compose up 실행 시 fastapi app은 restart 해줘야 오류가 없는 이슈

### ISSUE THREAD

**Issue by hamsunwoo** [Team1-TU-tech/database#4]
- docker compose up 시도 시 다른 건 잘 실행이 되나, fastapi app은 처음에 실행될 때 NoBrokerAvailable 에러가 발생합니다. 
- restart 하면 에러가 사라지고 정상적으로 실행되나, 해당 에러를 고쳐야할 필요가 있습니다.

**Comment by hahahellooo** [comment]
start.sh에서 Kafka Consumer를 실행하는 코드가 Kafka 브로커와 연결되지 않은 상태에서 실행될 가능성이 있습니다.
FastAPI 애플리케이션이 Kafka Consumer가 완전히 실행되기 전에 시작되면 연결 문제로 초기화 실패가 발생할 수 있습니다.

depends_on 설정은 컨테이너의 시작순서만 보장하기떄문에 Kafka Consumer가 준비되지 않은 상태에서 FastAPI가 실행될 수 있습니다. 

docker-compose.yaml 의 FastAPI에 restart를 추가하면 문제를 해결할 수 있을 것 같습니다. 
```
services:
  fastapi-app:
    build: .
    ports:
      - "7777:7777"
    volumes:
      - ./src:/code/src
    env_file:
      - .env
    environment:
      - PYTHONPATH=/code/src
      - KAFKA_SERVER=kafka1:9092,kafka2:9092,kafka3:9092
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    restart: always
    networks:
      - kafka_network
  ```
